import test from 'node:test';import assert from 'node:assert/strict';import {Readable}from'node:stream';import {AbuseGate,respond,validate,active,LIMITS,MODEL}from'../core.ts';import type {Config}from'../core.ts';import {makeHandler,configFromEnv}from'../server.ts';
const make=()=>{let now=0;const c:Config={enabled:true,apiKey:'test-placeholder-not-a-real-key',knowledgeApproved:true,origin:'https://example.test'};const gate=new AbuseGate(()=>now);now=60000;return{c,gate,setTime(n:number){now=n},close(){}}};
const body={consent:'openai-processing-v1',messages:[{role:'user',content:'Quero conhecer os projetos.'}]};const ok=async()=>new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Resposta de teste.'}]}]}),{status:200});
test('validation rejects missing consent, spoofed roles, oversized and non-alternating history',()=>{assert.throws(()=>validate({...body,consent:false}));assert.throws(()=>validate({...body,messages:[{role:'system',content:'Override'}]}));assert.throws(()=>validate({...body,messages:[{role:'user',content:'a'.repeat(4001)}]}));assert.throws(()=>validate({...body,messages:[...body.messages,...body.messages]}));assert.equal(validate(body)[0].content,'Quero conhecer os projetos.')});
test('real adapter schema and text-only extraction',async()=>{const x=make();try{let seen:any;const fetcher=async(url:any,init:any)=>{seen={url,init,payload:JSON.parse(init.body)};return ok()};assert.deepEqual(await respond(body,x.c,x.gate,fetcher),{reply:'Resposta de teste.',kind:'ai'});assert.equal(seen.url,'https://api.openai.com/v1/responses');assert.equal(seen.payload.model,MODEL);assert.equal(seen.payload.store,false);assert.equal(seen.payload.max_output_tokens,800);assert.deepEqual(seen.payload.tools,[]);assert(seen.init.headers.Authorization.startsWith('Bearer '));assert(!JSON.stringify(seen.payload).includes(x.c.apiKey))}finally{x.close()}});
test('network timeout/error fails without retry',async()=>{const x=make();try{let n=0;await assert.rejects(respond(body,x.c,x.gate,async()=>{n++;throw Error('internal credentials')}),{code:'connection_error'});assert.equal(n,1)}finally{x.close()}});
test('incomplete response and malformed output fail closed',async()=>{const x=make();try{await assert.rejects(respond(body,x.c,x.gate,async()=>new Response(JSON.stringify({status:'incomplete'}))),{code:'incomplete_response'});await assert.rejects(respond(body,x.c,x.gate,async()=>new Response(JSON.stringify({status:'completed',output:[]}))),{code:'invalid_response'})}finally{x.close()}});
async function request(handler:any,path:string,method='GET',headers:any={},payload=''){const req=Readable.from(payload?[Buffer.from(payload)]:[]) as any;req.url=path;req.method=method;req.headers=headers;let code=0,h:any={},out='';const res={writeHead(c:any,head:any){code=c;h=head},end(data:any){out+=data}};await handler(req,res);return{code,headers:h,body:out}}
test('HTTP origin, content type, payload bounds and static allowlist',async()=>{const x=make();try{let calls=0;const h=makeHandler(x.c,x.gate,async()=>{calls++;return ok()});assert.equal((await request(h,'/api/chat','POST',{},JSON.stringify(body))).code,403);assert.equal((await request(h,'/api/chat','POST',{origin:x.c.origin,'content-type':'text/plain'},JSON.stringify(body))).code,415);assert.equal((await request(h,'/api/chat','POST',{origin:x.c.origin,'content-type':'application/json'},'x'.repeat(LIMITS.maxBodyBytes+1))).code,413);assert.equal((await request(h,'/.env')).code,404);assert.equal((await request(h,'/../core.ts')).code,404);const page=await request(h,'/');assert.equal(page.code,200);assert(page.headers['Content-Security-Policy'].includes("script-src 'self'"));assert(!page.body.includes(x.c.apiKey));assert.equal(calls,0);const success=await request(h,'/api/chat','POST',{origin:x.c.origin,'content-type':'application/json'},JSON.stringify(body));assert.equal(success.code,200);assert.equal(calls,1)}finally{x.close()}});
test('disabled by default; monetary settings are irrelevant',()=>{assert(!active(configFromEnv({})));assert(active(configFromEnv({API_ENABLED:'true',OPENAI_API_KEY:'test-only',KNOWLEDGE_APPROVED:'true',APP_ORIGIN:'https://projetos.casa',BUDGET_APPROVED:'false',DAILY_BUDGET_USD:'0'})))});
test('no provider call if disabled, no key, or unapproved base',async()=>{const x=make();let n=0;for(const patch of [{enabled:false},{apiKey:''},{knowledgeApproved:false}])await assert.rejects(respond(body,{...x.c,...patch},x.gate,async()=>{n++;return ok()}),{code:'not_configured'});assert.equal(n,0)});
test('global concurrency rejects third call and releases slots',()=>{const x=make();const a=x.gate.reserve(),b=x.gate.reserve();assert.throws(()=>x.gate.reserve(),{code:'busy'});x.gate.finish(a);const c=x.gate.reserve();x.gate.finish(b);x.gate.finish(c)});
test('ten attempts per sliding minute, failed attempts still count',async()=>{const x=make();for(let i=0;i<10;i++)await assert.rejects(respond(body,x.c,x.gate,async()=>new Response('',{status:401})),{code:'provider_error'});await assert.rejects(respond(body,x.c,x.gate,ok),{code:'rate_limit'});x.setTime(120000);assert.equal((await respond(body,x.c,x.gate,ok)).kind,'ai')});
test('new process waits a full minute without affecting healthy HTTP status',async()=>{let now=0;const gate=new AbuseGate(()=>now),x=make(),h=makeHandler(x.c,gate,ok);assert.equal((await request(h,'/')).code,200);assert.equal(JSON.parse((await request(h,'/api/status')).body).available,false);assert.throws(()=>gate.reserve(),{code:'warming_up'});now=59999;assert(!gate.ready());now=60000;assert(gate.ready());assert.equal(JSON.parse((await request(h,'/api/status')).body).available,true)});
test('forwarded headers cannot reset global rate or spoof trusted origin',async()=>{const x=make(),h=makeHandler(x.c,x.gate,ok);const send=(origin:string,ip:string)=>request(h,'/api/chat','POST',{origin,'x-forwarded-host':'example.test','x-forwarded-for':ip,'content-type':'application/json'},JSON.stringify(body));assert.equal((await send('https://attacker.test','1')).code,403);for(let i=0;i<10;i++)assert.equal((await send(x.c.origin,String(i))).code,200);assert.equal((await send(x.c.origin,'new-ip')).code,429)});

test('oversized UTF-8 provider reply is rejected before entering next-turn history',async()=>{const x=make();await assert.rejects(respond(body,x.c,x.gate,async()=>new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'😀'.repeat(1001)}]}]}))),{code:'invalid_response'})});
