import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import vm from'node:vm';
class El{children:El[]=[];className='';textContent='';value='';checked=false;disabled=false;onclick:any;onchange:any;onsubmit:any;onkeydown:any;parent:El|null=null;appendChild(x:El){x.parent=this;this.children.push(x)}replaceChildren(){this.children=[]}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this)}focus(){} }
const tick=()=>new Promise(r=>setImmediate(r));
function setup(available=true,reply?:()=>Promise<Response>,starting=false){const ids:Record<string,El>={};for(const id of ['input','conversation','consent','status-badge','notice','form','reset','choices'])ids[id]=new El;const send=new El;let calls:any[]=[],timers:Array<()=>void>=[];const document={getElementById:(id:string)=>ids[id],querySelector:()=>send,querySelectorAll:()=>ids.choices.children,createElement:()=>new El};const fetch=async(url:string,init?:any)=>{calls.push({url,init});if(url==='/api/status')return new Response(JSON.stringify({available,starting}));return reply?reply():new Response(JSON.stringify({kind:'ai',reply:'Resposta do mock de teste.'}))};vm.runInNewContext(readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),{document,fetch,AbortController,TextEncoder,setTimeout:(f:()=>void)=>timers.push(f)});return{ids,send,calls,timers}}
test('UI does not send conversation before consent, and disabled state is honest',async()=>{const x=setup();await tick();assert(x.send.disabled);x.ids.input.value='Olá';x.ids.form.onsubmit({preventDefault(){}});await tick();assert.equal(x.calls.length,1);assert(x.ids.notice.textContent.includes('Autorize'));const y=setup(false);await tick();assert(y.ids.input.disabled);assert(y.ids.notice.textContent.includes('não usa respostas simuladas'))});
test('consented chat sends bounded history, safely renders answer and clears locally',async()=>{const x=setup();await tick();x.ids.consent.checked=true;x.ids.consent.onchange();x.ids.input.value='Quero um PWA';x.ids.form.onsubmit({preventDefault(){}});await tick();assert.equal(x.calls[1].url,'/api/chat');const payload=JSON.parse(x.calls[1].init.body);assert.equal(payload.consent,'openai-processing-v1');assert.equal(payload.messages[0].content,'Quero um PWA');assert.equal(x.ids.conversation.children.at(-1)?.textContent,'Resposta do mock de teste.');x.ids.reset.onclick();assert.equal(x.ids.conversation.children.length,0)});
test('reset during in-flight request cannot resurrect transcript',async()=>{let finish:any;const pending=new Promise<Response>(r=>finish=r);const x=setup(true,()=>pending);await tick();x.ids.consent.checked=true;x.ids.input.value='Olá';x.ids.form.onsubmit({preventDefault(){}});x.ids.reset.onclick();finish(new Response(JSON.stringify({kind:'ai',reply:'stale answer'})));await tick();assert.equal(x.ids.conversation.children.length,0)});
test('API errors restore text and never label scripted content as AI',async()=>{const x=setup(true,async()=>new Response(JSON.stringify({error:'not_configured',message:'A IA não está disponível.'}),{status:503}));await tick();x.ids.consent.checked=true;x.ids.input.value='Meu pedido';x.ids.form.onsubmit({preventDefault(){}});await tick();assert.equal(x.ids.input.value,'Meu pedido');assert.equal(x.ids.conversation.children[0].className,'message error');assert.equal(x.ids.conversation.children[0].textContent,'A IA não está disponível.')});

test('startup cooldown schedules a status recheck without sending a conversation',async()=>{const x=setup(false,undefined,true);await tick();assert(x.ids.input.disabled);assert.equal(x.timers.length,1);assert(x.ids.notice.textContent.includes('automaticamente'));x.timers[0]();await tick();assert(x.calls.every(c=>c.url==='/api/status'))});
